spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smartchat
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    # database-platform: org.hibernate.dialect.MySQL5Dialect

# MinIO Configuration
minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: talkative
