spring:
  application.name: Talkative

  profiles:
    active: dev

  server:
    port: 8000

server:
  servlet:
    context-path: /api/v1/

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    # 1h in millisecond
    expiration-time: 3600000
