spring:
  datasource:
    url: jdbc:mysql://mysql:3306/talkative  # Connecting to MySQL container
    username: user  # Use the credentials set in Docker Compose
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

# MinIO Configuration for Docker
minio:
  fetch-url: http://localhost:9000
  url: http://minio:9000  # MinIO service inside Docker Compose
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: talkative
